import {
  BaklavaDesktop,
  BaklavaMobile,
  BaklavaTablet,
  BaklavaThumbnail,
  BrownieDesktop,
  BrownieMobile,
  BrownieTablet,
  BrownieThumbnail,
  CakeDesktop,
  CakeMobile,
  CakeTablet,
  CakeThumbnail,
  CremeBruleeDesktop,
  CremeBruleeMobile,
  CremeBruleeTablet,
  CremeBruleeThumbnail,
  MacaronDesktop,
  MacaronMobile,
  MacaronTablet,
  MacaronThumbnail,
  MeringueDesktop,
  MeringueMobile,
  MeringueTablet,
  MeringueThumbnail,
  PannaCottaDesktop,
  PannaCottaMobile,
  PannaCottaTablet,
  PannaCottaThumbnail,
  TiramisuDesktop,
  TiramisuMobile,
  TiramisuTablet,
  TiramisuThumbnail,
  WaffleDesktop,
  WaffleMobile,
  WaffleTablet,
  WaffleThumbnail,
} from './images';

export const products = [
  {
    id: 1,
    image: {
      thumbnail: WaffleThumbnail,
      mobile: WaffleMobile,
      tablet: WaffleTablet,
      desktop: WaffleDesktop,
    },
    name: 'Waffle with Berries',
    category: 'Waffle',
    price: 6.5,
  },
  {
    id: 2,
    image: {
      thumbnail: CremeBruleeThumbnail,
      mobile: CremeBruleeMobile,
      tablet: CremeBruleeTablet,
      desktop: CremeBruleeDesktop,
    },
    name: 'Vanilla Bean Crème Brûlée',
    category: 'Crème Brûlée',
    price: 7.0,
  },
  {
    id: 3,
    image: {
      thumbnail: MacaronThumbnail,
      mobile: MacaronMobile,
      tablet: MacaronTablet,
      desktop: MacaronDesktop,
    },
    name: 'Macaron Mix of Five',
    category: 'Macaron',
    price: 8.0,
  },
  {
    id: 4,
    image: {
      thumbnail: TiramisuThumbnail,
      mobile: TiramisuMobile,
      tablet: TiramisuTablet,
      desktop: TiramisuDesktop,
    },
    name: 'Classic Tiramisu',
    category: 'Tiramisu',
    price: 5.5,
  },
  {
    id: 5,
    image: {
      thumbnail: BaklavaThumbnail,
      mobile: BaklavaMobile,
      tablet: BaklavaTablet,
      desktop: BaklavaDesktop,
    },
    name: 'Pistachio Baklava',
    category: 'Baklava',
    price: 4.0,
  },
  {
    id: 6,
    image: {
      thumbnail: MeringueThumbnail,
      mobile: MeringueMobile,
      tablet: MeringueTablet,
      desktop: MeringueDesktop,
    },
    name: 'Lemon Meringue Pie',
    category: 'Pie',
    price: 5.0,
  },
  {
    id: 7,
    image: {
      thumbnail: CakeThumbnail,
      mobile: CakeMobile,
      tablet: CakeTablet,
      desktop: CakeDesktop,
    },
    name: 'Red Velvet Cake',
    category: 'Cake',
    price: 4.5,
  },
  {
    id: 8,
    image: {
      thumbnail: BrownieThumbnail,
      mobile: BrownieMobile,
      tablet: BrownieTablet,
      desktop: BrownieDesktop,
    },
    name: 'Salted Caramel Brownie',
    category: 'Brownie',
    price: 4.5,
  },
  {
    id: 9,
    image: {
      thumbnail: PannaCottaThumbnail,
      mobile: PannaCottaMobile,
      tablet: PannaCottaTablet,
      desktop: PannaCottaDesktop,
    },
    name: 'Vanilla Panna Cotta',
    category: 'Panna Cotta',
    price: 6.5,
  },
];
